/**
 * Franchise management.
 *
 * Franchisees are businesses that recruit and manage drivers under the Velocity
 * platform. Each franchise earns 5% of every fare generated by their drivers.
 * That 5% comes from Velocity's platform commission, not the driver's payout.
 */
import { onCall } from 'firebase-functions/v2/https';
import { logger } from 'firebase-functions';
import { z } from 'zod';

import { db, FieldValue } from '../lib/firebase';
import { requireAdmin, invalid } from '../lib/guards';

const createFranchiseSchema = z.object({
  name:         z.string().min(2).max(120),
  ownerName:    z.string().min(2).max(120),
  email:        z.string().email().max(200),
  phone:        z.string().max(20).optional(),
  city:         z.string().max(80).optional(),
  commissionRate: z.number().min(0).max(0.5).optional(), // defaults to 0.05
});

/** Admin-only: create a new franchise. */
export const adminCreateFranchise = onCall(async (req) => {
  const admin = requireAdmin(req);
  const parsed = createFranchiseSchema.safeParse(req.data);
  if (!parsed.success) {
    invalid(parsed.error.issues[0]?.message ?? 'Invalid franchise details.');
  }
  const data = parsed.data;

  const ref = db.collection('franchises').doc();
  const now = FieldValue.serverTimestamp();

  await ref.set({
    id: ref.id,
    name: data.name,
    ownerName: data.ownerName,
    email: data.email,
    phone: data.phone ?? null,
    city: data.city ?? null,
    commissionRate: data.commissionRate ?? 0.05,
    totalDrivers: 0,
    cycleRevenue: 0,
    totalRevenue: 0,
    createdBy: admin.uid,
    createdAt: now,
    updatedAt: now,
  });

  await db.collection('auditLogs').add({
    type: 'franchise.created',
    actor: admin.uid,
    franchiseId: ref.id,
    createdAt: now,
  });

  logger.info('Franchise created', { actor: admin.uid, franchiseId: ref.id });
  return { ok: true, franchiseId: ref.id };
});

const assignFranchiseSchema = z.object({
  driverId:    z.string().min(1).max(128),
  franchiseId: z.string().min(1).max(128).nullable(),
});

/** Admin-only: assign or unassign a driver to/from a franchise. */
export const adminAssignFranchise = onCall(async (req) => {
  const admin = requireAdmin(req);
  const parsed = assignFranchiseSchema.safeParse(req.data);
  if (!parsed.success) invalid('Provide a valid driverId and franchiseId.');
  const { driverId, franchiseId } = parsed.data;

  const driverRef = db.doc(`drivers/${driverId}`);
  const snap = await driverRef.get();
  if (!snap.exists) invalid('Driver not found.');

  const prevFranchiseId = snap.get('franchiseId') as string | null;
  const now = FieldValue.serverTimestamp();
  const batch = db.batch();

  batch.set(driverRef, { franchiseId: franchiseId ?? null, updatedAt: now }, { merge: true });

  if (prevFranchiseId && prevFranchiseId !== franchiseId) {
    batch.set(
      db.doc(`franchises/${prevFranchiseId}`),
      { totalDrivers: FieldValue.increment(-1), updatedAt: now },
      { merge: true },
    );
  }
  if (franchiseId && franchiseId !== prevFranchiseId) {
    batch.set(
      db.doc(`franchises/${franchiseId}`),
      { totalDrivers: FieldValue.increment(1), updatedAt: now },
      { merge: true },
    );
  }

  await batch.commit();
  logger.info('Franchise assignment updated', { actor: admin.uid, driverId, franchiseId });
  return { ok: true };
});
