# ---------------------------------------------------------------------------
# Velocity release-build keep rules (R8).
#
# Appended to android/app/proguard-rules.pro by plugins/withProguardRules.js,
# because android/ is generated by `expo prebuild` and is not in git.
#
# Why this file exists: Google Play's "App optimization" panel measures how
# much of the shipped DEX is obfuscated. With minification off it reads ~1%,
# which is under the 25% threshold Play warns about and can hold publishing
# back. Turning R8 on (android.enableMinifyInReleaseBuilds, set in
# plugins/withGradleConfig.js) is what actually raises that number; the rules
# below are the safety net for the parts of a React Native app that are found
# by NAME at runtime and would otherwise be renamed out from under whatever
# looks them up.
#
# React Native, expo-modules-core, expo-updates, expo-notifications,
# react-native-svg, Firebase and Play Services all ship consumer rules inside
# their own AARs, so this file deliberately only covers what those miss. Do
# not add blanket `-keep class **` rules here: every class kept by name is a
# class that stays unobfuscated, which is the metric we are trying to move.
# ---------------------------------------------------------------------------

# Crash reports. R8 in full mode (the AGP default) drops these attributes
# unless they are asked for by name, and without them every Play Console stack
# trace loses its line numbers. AGP writes the mapping file into the AAB, so
# Play still de-obfuscates the frames — keeping these costs no obfuscation.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Reflection metadata. Expo's Kotlin module layer reads generic types and
# annotations at runtime (Record fields, Enumerable enums, view prop setters),
# and full mode strips those attributes by default. The failure mode is not a
# crash but a native module that silently rejects its arguments, which is far
# harder to spot in a store build.
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod
-keepattributes RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations
-keep class kotlin.Metadata { *; }

# Fragments are re-created by the framework from their class name after the
# process is killed in the background — @react-native-community/datetimepicker
# and the image/document pickers all put one on screen, so a renamed Fragment
# is a crash on resume rather than at launch.
-keep public class * extends androidx.fragment.app.Fragment

# Optional dependencies that OkHttp and friends reference but never ship.
# AGP 8 fails the release build on unresolved references rather than warning,
# and none of these are on any code path we execute.
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
